version: '2'

services:
  web:
    build: .
# Uncomment this to allow the HOST to connect.
#    ports:
#      - "8080:8080"
# Enables intra-container communications.
    expose:
      - "8080"
#  proxy:
#  	image: rollo/myzap
#    image: owasp/zap2docker-stable
#    volumes:
#    - /tmp/.X11-unix:/tmp/.X11-unix:ro
#    privileged: true
#    environment:
#    - DISPLAY=$DISPLAY
#    depends_on:
#      - web
  client:
    image: rollo/myfirefox
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
    privileged: true
    environment:
    - DISPLAY=$DISPLAY
    depends_on:
      - web

# Wait until the 'web' container is running
#    command:
#      - /usr/bin/firefox http://mywebgoat_web_1:8080/WebGoat
