# Set of services that builds a TeamCity build chain.
version: '2'

services:
  git:
    image: "store/gitlab/gitlab-ce:8.13.1-ce.0"

  artifactory:
    image: "mattgruter/artifactory"

  #protex:
#    image: "rollo/protex:alpine"

  #klocwork:
#   image: "rollo/klocwork:alpine"

  teamcity-server:
    image: "jetbrains/teamcity-server"
#e.g. $ docker run -dt --name teamcity -p 8111:8111 sjoerdmulder/teamcity
#e.g. hackity hack: https://lostechies.com/gabrielschenker/2016/04/01/ci-with-teamcity-and-docker-part-3/

  teamcity-agent:
    image: "jetbrains/teamcity-agent"
#e.g. $ docker run -d --name=teamcity-agent-1 --link teamcity:teamcity --privileged -e TEAMCITY_SERVER=http://teamcity:8111 sjoerdmulder/teamcity-agent:latest

  jenkins:
    image: "jenkins"

  robot-framework:
    image: "manycoding/robotframework"

  golang:
    image: "golang"

network:

volumes:
