FROM alpine:3.3
MAINTAINER Christopher Rollo (rollo.nike@gmail.com)
# Update the OS
RUN apk upgrade && rm -rf /var/cache/apk/*
# Set the environment
# Install apps
# Create Userspace
# Get to it
CMD /bin/ash
